name: cmeutils
channels:
  - conda-forge
dependencies:
  - freud
  - gsd>2.0,<3.0
  - hoomd>3.0=*cpu*
  - mbuild
  - numpy
  - pip
  - python
  - matplotlib
  - mdanalysis
  - pymbar >= 4.0
  - pytest
  - pytest-cov
  - rowan
